import {Image, Pressable, Text, View} from "react-native"
import React, {useRef, useMemo, useCallback, useState} from "react"
import {KeyboardAwareScrollView} from "react-native-keyboard-aware-scroll-view"
import {FONTS, SIZES} from "../../constants/theme"
import icons from "../../constants/icons"
import {Formik} from "formik"
import CustomInput from "../../components/CustomInput"
import CustomButton from "../../components/CustomButton"
import BottomSheet, {BottomSheetBackdrop} from "@gorhom/bottom-sheet"
import InputBox from "../../components/InputBox"
import OTPInputView from "@twotalltotems/react-native-otp-input"
import {useNavigation} from "@react-navigation/native"
import {LoginStyles as styles} from "./styles"
import {LOGIN_SCREEN, SIGNUP_SCREEN} from "../../constants/screens"
import * as yup from "yup"
import {useAuthApis} from "../../services/api/auth/auth.index"
import {useMutation} from "react-query"
import {FLUSDYNAMIC_STORE, useFlusDispatcher, useFlusStores} from "react-flus"
import {USER_LOGIN} from "../../flus/constants/auth.const"
import {getDeviceName} from "react-native-device-info"
import {accountLoginValidationSchema, forgetPwdValidationSchema, resetPwdValidationSchema} from "../../utils/validation"

const Login = () => {
